tds_id = "DE_AC01"
ixl_id = "DE_IXL01"
rasta_id = "256"
ixl_address = "http://127.0.0.1:5100"
timeout = 5000

[trustworthy]
tds_id = "DE_AC01"
ixl_id = "DE_IXL01"
ixl_address = "0.0.0.0:8001"

[unreliable]
tds_id = "DE_AC01"
ixl_id = "DE_IXL01"
ixl_address = "0.0.0.0:8002"
