rasta_id = "256"
ixl_address = "http://127.0.0.1:5100"
ixl_delay = 10000
timeout = 5000
strategy = "TryUnreliable"

[trustworthy]
ixl_address = "0.0.0.0:8001"

[unreliable]
ixl_address = "0.0.0.0:8002"
